### ISSUE TITLE
Preview not saved if the source title exceeds 255 characters

### ISSUE THREAD

**Issue by sir1ke** [humhub/humhub-modules-linkpreview#43] opened 2024-07-20 08:03 UTC
Hi,

the instagram integration it self works fine, but the way the title is generated makes it conflict with the title limit of 255 Characters.
![image](https://github.com/user-attachments/assets/5d277404-e834-4dc1-9fa0-598b3cc529f8)
which results in a boring link
![image](https://github.com/user-attachments/assets/946e13c9-1c66-4738-b6ea-1f4ba724befb)

On very small descriptions it works fine though
![image](https://github.com/user-attachments/assets/974b705e-02f9-4b02-931d-19c1fc180bfe)

I see different options, truncate, change generation style, allow editing to keep the limit.
I personally would vote for a truncate option.

**Comment by marc-farre** [comment] 2024-07-21 09:35
@sir1ke Are you using the latest 2.0.3 version?
If yes, can you provide the URL so I can do some tests? Thanks.

**Comment by sir1ke** [comment] 2024-07-25 20:23
@marc-farre Yeah im running the latest version.

Example link:
https://www.instagram.com/p/C92Ee6QqY0R/

**Comment by marc-farre** [comment] 2024-07-26 15:54
@sir1ke Thanks for the link.

@luke- I can reproduce the issue. It's because the title is more than 255 chars.
I think we should keep this rule, but instead of no preview at all, what do you think about truncating the title with `StringHelper::truncate($title, 250, '[...]')` when retrieving it from the web page?

**Comment by luke-** [comment] 2024-07-30 09:13
Truncating would be fine for me!

**Comment by marc-farre** [comment] 2024-07-30 14:30
@luke- PR https://github.com/humhub/linkpreview/pull/22

@sir1ke when the new version of the module will be released, the title will be truncated:
![image](https://github.com/user-attachments/assets/d5aefef9-e08a-4248-aa7d-0320f77698d3)

**Comment by luke-** [comment] 2024-07-30 15:58
Just released 2.0.4

**Closed as completed by luke-** 2024-07-30 15:58 UTC
